# Docker compose 버전
version: '3.8'
# 가동할 컨테이너 목록
services:
  db:
    # 사용할 이미지(Docker Hub 또는 로컬에 저장된 Image)
    image: mysql:8.0
    container_name: gaon_db
    restart: always
    # 외부에서 컨테이너 내부로 연결되는 포트 목록
    ports:
      - 32000:3306
    # 컨테이너 내에서 사용되는 환경 변수
    environment:
      # <설정한 Database root 계정 비밀 번호>
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    privileged: true
    # 실제 드라이브와 컨테이너의 드라이브를 연결(Mount)
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    # 컨테이너 내부에서 사용되는 네트워크
    networks:
      - backend
  # kurento 부분, 나중에 AWS설정 후에 다시 해보기
  # kurento:
  #   image: kurento/kurento-media-server:latest
  #   restart: always
  #   ports:
  #     - '8888:8888'
  #   environment:
  #     TZ: 'Asia/Seoul'
  #     # <TURN 서버가 기동되는 퍼블릭 Ipv4 주소>
  #     KMS_STUN_IP: i5b101.p.ssafy.io
  #     KMS_STUN_PORT: '3478'
  #     KMS_TURN_URL: 'root:dlfgo101@i5b101.p.ssafy.io:3478?transport=udp'
  #   networks:
  #     - backend
  app:
    # 공개된 Image 가 아닌 Dockerfile 을 통한 빌드 이미지 사용
    build:
      context: ./
    restart: always
    container_name: gaon_app
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      TZ: Asia/Seoul
      # 수정사항
      #Spring application.properties DB 설정
      #  SPRING_DATASOURCE_URL: 'jdbc:mysql://localhost:3306/gaon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/gaon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true'
      # Kurento Media Client 동작을 위한 Kurento Media Server URL 설정
      # JAVA_TOOL_OPTIONS: '-Dkms.url=ws://kurento:8888/kurento'
      server.address: 0.0.0.0
      # 의존 컨테이너
    depends_on:
      - db
    #   - kurento
    networks:
      - backend
networks:
  backend:
